// AUTO-GENERATED by esp32/tools/train_export.py - do not edit.
#ifndef RLM_CONFIG_H
#define RLM_CONFIG_H

#define RLM_VOCAB_ROWS   4096
#define RLM_DIM          96
#define RLM_MAX_SEQ      96
#define RLM_HEADS        4
#define RLM_HEAD_DIM     (RLM_DIM / RLM_HEADS)
#define RLM_FFN          384
#define RLM_GATE_HID     48
#define RLM_CLASSES      2
#define RLM_MAX_RECURSION 8
#define RLM_MIN_RECURSION 2
#define RLM_HALT_EPS 0.1f
#define RLM_TAU_LO         0.347f
#define RLM_LN_EPS       1e-5f
#define RLM_REFINE_GAIN  0.1f

#endif  // RLM_CONFIG_H
